name: docker build and push to docker hup

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs: 
  build_Docker:
    runs-on: ubuntu-latest

    steps: 

      - name: checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.docker_user }}
          password: ${{ secrets.docker_password }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: 76768787/server-rest-api:${{ github.sha }}      
